name: devtrack
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
  geolocator: ^14.0.0
  image_picker: ^1.1.2
  latlong2: ^0.9.1
  flutter_map: ^8.1.1

  
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  path: ^1.9.1
  shared_preferences: ^2.5.3
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/logo.png

 